// Milestones Map — full 0-12 month dataset for the clickable prototype.
// Source of truth: mvp_0_12_months_map.csv (milestones) and
// activity_library_0_12_months.csv (activities). Domains use parent-friendly labels.

const AGES = [2, 4, 6, 9, 12];

const AGE_LABELS = {
  2: "2 months",
  4: "4 months",
  6: "6 months",
  9: "9 months",
  12: "12 months"
};

const MILESTONES_BY_AGE = {
  2: [
    { id: "ms_002_social_001", domain: "Social & Emotional", title: "Settles with caregiver support", text: "Baby may calm when spoken to, held, or picked up.", source: "CDC 2 months" },
    { id: "ms_002_social_002", domain: "Social & Emotional", title: "Looks toward faces", text: "Baby watches a caregiver's face during close routines.", source: "CDC 2 months" },
    { id: "ms_002_social_003", domain: "Social & Emotional", title: "Responds with early smiles", text: "Baby may smile during warm face-to-face interaction.", source: "CDC 2 months" },
    { id: "ms_002_language_001", domain: "Language & Communication", title: "Makes non-crying sounds", text: "Baby makes small sounds beyond crying.", source: "CDC 2 months" },
    { id: "ms_002_language_002", domain: "Language & Communication", title: "Responds to loud sound", text: "Baby startles, quiets, or changes movement after a loud sound.", source: "CDC 2 months" },
    { id: "ms_002_cognitive_001", domain: "Learning & Thinking", title: "Tracks caregiver movement", text: "Baby watches as a caregiver moves nearby.", source: "CDC 2 months" },
    { id: "ms_002_cognitive_002", domain: "Learning & Thinking", title: "Looks briefly at a toy", text: "Baby focuses on a toy for a short moment.", source: "CDC 2 months" },
    { id: "ms_002_movement_001", domain: "Movement & Physical", title: "Lifts head during awake tummy time", text: "Baby raises head briefly while awake on tummy.", source: "CDC + WHO motor" },
    { id: "ms_002_movement_002", domain: "Movement & Physical", title: "Moves arms and legs on both sides", text: "Baby moves both arms and both legs during awake time.", source: "CDC + WHO motor" },
    { id: "ms_002_movement_003", domain: "Movement & Physical", title: "Briefly opens hands", text: "Baby's hands sometimes open rather than staying tightly fisted.", source: "CDC 2 months" }
  ],
  4: [
    { id: "ms_004_social_001", domain: "Social & Emotional", title: "Smiles to engage caregiver", text: "Baby smiles to get or keep your attention.", source: "CDC 4 months" },
    { id: "ms_004_social_002", domain: "Social & Emotional", title: "Begins early laughing response", text: "Baby may chuckle when you playfully engage.", source: "CDC 4 months" },
    { id: "ms_004_social_003", domain: "Social & Emotional", title: "Seeks attention with face, body, or sounds", text: "Baby looks, moves, or vocalizes to keep interaction going.", source: "CDC + Harvard" },
    { id: "ms_004_language_001", domain: "Language & Communication", title: "Cooing sounds emerge", text: "Baby makes vowel-like sounds.", source: "CDC + Harvard" },
    { id: "ms_004_language_002", domain: "Language & Communication", title: "Responds vocally to your voice", text: "Baby makes sounds back when you talk.", source: "CDC + Harvard" },
    { id: "ms_004_language_003", domain: "Language & Communication", title: "Turns toward familiar voice", text: "Baby turns head toward your voice.", source: "CDC 4 months" },
    { id: "ms_004_cognitive_001", domain: "Learning & Thinking", title: "Anticipates feeding cue", text: "Baby opens mouth when seeing breast or bottle if hungry.", source: "CDC 4 months" },
    { id: "ms_004_cognitive_002", domain: "Learning & Thinking", title: "Studies own hands", text: "Baby looks at hands with interest.", source: "CDC 4 months" },
    { id: "ms_004_movement_001", domain: "Movement & Physical", title: "Holds head steady with support", text: "Baby keeps head steadier while being held.", source: "CDC + WHO motor" },
    { id: "ms_004_movement_002", domain: "Movement & Physical", title: "Uses hands toward mouth or toys", text: "Baby brings hands to mouth, holds placed toy, or bats at toys.", source: "CDC 4 months" },
    { id: "ms_004_movement_003", domain: "Movement & Physical", title: "Pushes on forearms during tummy time", text: "Baby lifts chest using elbows/forearms while awake on tummy.", source: "CDC + WHO motor" }
  ],
  6: [
    { id: "ms_006_social_001", domain: "Social & Emotional", title: "Recognizes familiar people", text: "Baby responds differently to people they know well.", source: "CDC 6 months" },
    { id: "ms_006_social_002", domain: "Social & Emotional", title: "Enjoys mirror interaction", text: "Baby looks at or reacts to their reflection.", source: "CDC 6 months" },
    { id: "ms_006_social_003", domain: "Social & Emotional", title: "Laughs during play", text: "Baby laughs or shows clear joy in interaction.", source: "CDC 6 months" },
    { id: "ms_006_language_001", domain: "Language & Communication", title: "Takes turns with sounds", text: "Baby makes a sound, waits, or responds after you copy it.", source: "CDC + Harvard" },
    { id: "ms_006_language_002", domain: "Language & Communication", title: "Explores playful mouth sounds", text: "Baby makes bubbly, squealing, or raspberry-like sounds.", source: "CDC 6 months" },
    { id: "ms_006_cognitive_001", domain: "Learning & Thinking", title: "Explores objects with mouth", text: "Baby safely mouths toys to learn about shape and texture.", source: "CDC 6 months" },
    { id: "ms_006_cognitive_002", domain: "Learning & Thinking", title: "Reaches for wanted toy", text: "Baby reaches toward a toy or object they want.", source: "CDC 6 months" },
    { id: "ms_006_cognitive_003", domain: "Learning & Thinking", title: "Shows stopping cue during feeding", text: "Baby closes mouth, turns away, or pauses when they do not want more.", source: "CDC + WHO" },
    { id: "ms_006_movement_001", domain: "Movement & Physical", title: "Rolls from tummy toward back", text: "Baby rolls or starts rolling from tummy to back.", source: "CDC + WHO motor" },
    { id: "ms_006_movement_002", domain: "Movement & Physical", title: "Pushes up during tummy play", text: "Baby pushes chest up with straighter arms while awake on tummy.", source: "CDC + WHO motor" },
    { id: "ms_006_movement_003", domain: "Movement & Physical", title: "Leans on hands while sitting", text: "Baby uses hands to support the body in sitting.", source: "CDC + WHO motor" }
  ],
  9: [
    { id: "ms_009_social_001", domain: "Social & Emotional", title: "Shows stranger awareness", text: "Baby may become shy, clingy, or cautious with unfamiliar people.", source: "CDC 9 months" },
    { id: "ms_009_social_002", domain: "Social & Emotional", title: "Uses varied facial expressions", text: "Baby shows multiple expressions during the day.", source: "CDC 9 months" },
    { id: "ms_009_social_003", domain: "Social & Emotional", title: "Responds to name", text: "Baby looks or reacts when called by name.", source: "CDC 9 months" },
    { id: "ms_009_social_004", domain: "Social & Emotional", title: "Reacts to caregiver leaving", text: "Baby looks, reaches, or cries when caregiver leaves.", source: "CDC 9 months" },
    { id: "ms_009_social_005", domain: "Social & Emotional", title: "Enjoys peekaboo-style social play", text: "Baby smiles, laughs, looks, or anticipates when you play peekaboo.", source: "CDC + Harvard" },
    { id: "ms_009_language_001", domain: "Language & Communication", title: "Repeats sound strings", text: "Baby makes repeated syllable-like sound strings.", source: "CDC + Harvard" },
    { id: "ms_009_language_002", domain: "Language & Communication", title: "Uses arms to request pickup", text: "Baby lifts arms or gestures to be picked up.", source: "CDC 9 months" },
    { id: "ms_009_cognitive_001", domain: "Learning & Thinking", title: "Looks for dropped or hidden object", text: "Baby searches for object after it goes out of sight.", source: "CDC 9 months" },
    { id: "ms_009_cognitive_002", domain: "Learning & Thinking", title: "Bangs objects together", text: "Baby explores by banging two safe objects.", source: "CDC 9 months" },
    { id: "ms_009_movement_001", domain: "Movement & Physical", title: "Gets into sitting", text: "Baby moves into sitting independently.", source: "CDC + WHO motor" },
    { id: "ms_009_movement_002", domain: "Movement & Physical", title: "Transfers objects between hands", text: "Baby moves a toy from one hand to the other.", source: "CDC 9 months" },
    { id: "ms_009_movement_003", domain: "Movement & Physical", title: "Rakes small safe food", text: "Baby uses fingers to rake food toward self.", source: "CDC 9 months" },
    { id: "ms_009_movement_004", domain: "Movement & Physical", title: "Sits without support", text: "Baby sits without hand support for a period.", source: "CDC + WHO motor" }
  ],
  12: [
    { id: "ms_012_social_001", domain: "Social & Emotional", title: "Plays simple social games", text: "Baby joins games like clapping, peekaboo, or turn-taking routines.", source: "CDC + Harvard" },
    { id: "ms_012_language_001", domain: "Language & Communication", title: "Waves or uses goodbye gesture", text: "Baby may wave or use a familiar gesture when someone leaves.", source: "CDC 12 months" },
    { id: "ms_012_language_002", domain: "Language & Communication", title: "Uses special name for parent", text: "Baby says or approximates a special caregiver name.", source: "CDC 12 months" },
    { id: "ms_012_language_003", domain: "Language & Communication", title: "Pauses to simple boundary word", text: "Baby pauses or stops briefly when caregiver says no.", source: "CDC 12 months" },
    { id: "ms_012_cognitive_001", domain: "Learning & Thinking", title: "Puts object into container", text: "Baby places an object into a cup, box, or container.", source: "CDC 12 months" },
    { id: "ms_012_cognitive_002", domain: "Learning & Thinking", title: "Finds a hidden object", text: "Baby looks for a toy hidden under cloth or container.", source: "CDC 12 months" },
    { id: "ms_012_movement_001", domain: "Movement & Physical", title: "Pulls to stand", text: "Baby pulls up using stable furniture or caregiver support.", source: "CDC + WHO motor" },
    { id: "ms_012_movement_002", domain: "Movement & Physical", title: "Cruises along support", text: "Baby walks while holding furniture.", source: "CDC + WHO motor" },
    { id: "ms_012_movement_003", domain: "Movement & Physical", title: "Uses early pincer grasp", text: "Baby picks up small safe food with thumb and index finger.", source: "CDC 12 months" }
  ]
};

const ACTIVITIES_BY_AGE = {
  2: [
    { id: "act_002_social_001", supports: ["ms_002_social_001"], evidence: "Mechanism-based", source: "WHO + Harvard", title: "Soft Voice Hold Pause", domain: "Social", time: "1-3 minutes", materials: "none", why: "Warm responsive caregiving supports safety and regulation during early routines.", steps: ["Hold baby comfortably, supporting head and neck.", "Speak softly and pause.", "Watch baby's face and body.", "Adjust your voice or hold to what baby shows."], stop: "Stop if baby seems uncomfortable, hungry, hot, cold, or hard to soothe." },
    { id: "act_002_social_002", supports: ["ms_002_social_002","ms_002_social_003"], evidence: "Mechanism-based", source: "Harvard + WHO", title: "Face-to-Face Pause", domain: "Social", time: "1-2 minutes", materials: "none", why: "Face-focused interaction supports early social attention and caregiver responsiveness.", steps: ["Place baby close enough to see your face during a calm awake moment.", "Look at baby and smile gently.", "Pause and wait.", "Respond to any look or movement."], stop: "Stop if baby turns away, fusses, or seems overstimulated." },
    { id: "act_002_language_001", supports: ["ms_002_language_001"], evidence: "Mechanism-based", source: "Harvard + CDC", title: "Copy Baby's Coos", domain: "Language", time: "1-3 minutes", materials: "none", why: "Back-and-forth sound play supports early communication turn-taking.", steps: ["Hold baby where they can hear and see you.", "Wait for a sound.", "Copy it softly and pause.", "Respond again when baby answers."], stop: "Stop if baby cries, coughs, turns away, or seems tired." },
    { id: "act_002_language_002", supports: ["ms_002_language_002"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Sound Noticing Routine", domain: "Language", time: "1 minute", materials: "soft household sound", why: "Naming everyday sounds supports auditory attention and caregiver observation.", steps: ["Use a gentle, normal household sound nearby.", "Say what the sound is.", "Watch baby's response.", "Notice one natural sound during the day."], stop: "Do not create loud sounds near baby. Discuss any lack of response with a provider." },
    { id: "act_002_cognitive_001", supports: ["ms_002_cognitive_001"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Slow Face Tracking", domain: "Learning", time: "1-2 minutes", materials: "none", why: "Slow visual social routines support attention and caregiver observation.", steps: ["Hold baby calm and awake on back or in arms.", "Move your face slowly from center to one side.", "Move back to center.", "Smile and pause."], stop: "Stop if baby fusses or looks away repeatedly." },
    { id: "act_002_movement_002", supports: ["ms_002_movement_003"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Gentle Hand Opening Play", domain: "Movement", time: "1-2 minutes", materials: "none or soft cloth", why: "Gentle touch along the hand supports hand opening and early grasp readiness.", steps: ["Wait for a calm awake moment.","Gently stroke the back of the hand from wrist to fingers.","Pause and watch the fingers open.","Offer your finger or a soft cloth to hold."], stop: "Never force the hand open. Stop if baby resists or fusses." },
    { id: "act_002_cognitive_002", supports: ["ms_002_cognitive_002"], evidence: "Mechanism-based", source: "CDC + WHO", title: "High-Contrast Toy Pause", domain: "Learning", time: "1-2 minutes", materials: "high-contrast toy or card", why: "Brief visual focus on a simple high-contrast object supports early attention and looking.", steps: ["Hold baby calm and awake.","Show a simple high-contrast toy about 20-30 cm away.","Hold it still and let baby look.","Move it slowly once baby fixes their gaze."], stop: "Stop if baby looks away, fusses, or seems tired." },
    { id: "act_002_movement_001", supports: ["ms_002_movement_001","ms_002_movement_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Mini Tummy Moment", domain: "Movement", time: "30 seconds-2 minutes", materials: "blanket", why: "Brief supervised prone play supports early head and trunk control.", steps: ["Place baby awake and supervised on tummy on a firm safe surface.", "Get low and talk softly.", "Show your face or a toy.", "Stop before baby is upset."], stop: "Only awake and supervised. Stop if distressed or sleepy. Never use for sleep." }
  ],
  4: [
    { id: "act_004_social_001", supports: ["ms_004_social_001","ms_004_social_003"], evidence: "Mechanism-based", source: "Harvard + CDC", title: "Smile-Copy Game", domain: "Social", time: "2-3 minutes", materials: "none", why: "Responsive imitation supports social attention and turn-taking.", steps: ["Sit with baby facing you during calm awake time.", "Smile and wait.", "Copy baby's expression or movement.", "Pause for a response."], stop: "Stop if baby looks away, arches, cries, or seems overstimulated." },
    { id: "act_004_social_002", supports: ["ms_004_social_002"], evidence: "Mechanism-based", source: "Harvard + CDC", title: "Gentle Funny-Face Pause", domain: "Social", time: "2-3 minutes", materials: "none", why: "Playful, gentle surprises in warm interaction can invite early chuckles and social engagement.", steps: ["Face baby during a happy, alert moment.","Make a soft playful sound or gentle funny face.","Pause and wait.","Respond warmly to any smile, chuckle, or movement."], stop: "Stop if baby looks away, arches, or seems overstimulated." },
    { id: "act_004_language_001", supports: ["ms_004_language_001","ms_004_language_002"], evidence: "Mechanism-based", source: "Harvard + CDC", title: "Coo Conversation", domain: "Language", time: "2-4 minutes", materials: "none", why: "Sound exchange supports early vocal turn-taking and communication attention.", steps: ["Hold baby where your face is visible.", "Make a soft vowel sound and wait.", "Copy baby's sound.", "Pause again for a response."], stop: "Stop if baby is tired, hungry, or upset." },
    { id: "act_004_language_002", supports: ["ms_004_language_003"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Voice From Side", domain: "Language", time: "1-2 minutes", materials: "none", why: "Everyday voice routines support auditory attention and caregiver observation.", steps: ["When baby is awake, speak gently from one side at a normal volume.", "Say baby's name or a short phrase.", "Wait for a response.", "Try the other side later."], stop: "Do not use loud sounds. Discuss any lack of sound response with a provider." },
    { id: "act_004_cognitive_001", supports: ["ms_004_cognitive_002","ms_004_movement_002"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Hand Watching Game", domain: "Learning", time: "2-3 minutes", materials: "none", why: "Hand watching supports body awareness and early exploration.", steps: ["Place baby on back or supported in arms.", "Bring baby's hands into view gently.", "Name the hands.", "Pause for looking."], stop: "Do not force hands open. Stop if baby resists." },
    { id: "act_004_cognitive_002", supports: ["ms_004_movement_002","ms_004_cognitive_002"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Safe Mouth Explore", domain: "Learning", time: "2-5 minutes", materials: "large safe teether", why: "Mouthing safe objects supports sensory exploration and hand-mouth coordination.", steps: ["Offer one clean baby-safe object too large to choke.", "Let baby look and touch.", "Let baby mouth it safely.", "Name the texture and object."], stop: "Use only age-safe objects. Supervise. Stop if gagging or distress occurs." },
    { id: "act_004_movement_002", supports: ["ms_004_movement_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Reach and Hold Play", domain: "Movement", time: "2-4 minutes", materials: "one light easy-grip toy", why: "Offering a light toy at midline supports reaching, grasping and hand-to-mouth coordination.", steps: ["Place baby on back or supported.","Hold a light toy within arm’s reach at the middle.","Let baby look, reach, and grasp.","Let baby bring it toward the mouth if safe."], stop: "Use only large safe toys. Supervise. Stop if baby is tired or frustrated." },
    { id: "act_004_movement_001", supports: ["ms_004_movement_003","ms_004_movement_001"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Forearm Tummy Play", domain: "Movement", time: "2-5 minutes", materials: "blanket and safe toy", why: "Prone play supports head, shoulder and trunk control.", steps: ["Place baby awake and supervised on tummy.", "Put a toy or your face in front.", "Encourage looking.", "Keep the session brief."], stop: "Awake supervised only. Stop if distressed. Never use for sleep." }
  ],
  6: [
    { id: "act_006_social_001", supports: ["ms_006_social_001"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Familiar Face Greeting", domain: "Social", time: "2 minutes", materials: "none", why: "Predictable greetings support recognition, social attention and responsive routines.", steps: ["Have a familiar caregiver enter calmly during awake time.", "Say hello and pause.", "Let baby look and respond.", "Name the person."], stop: "Stop if baby becomes overwhelmed." },
    { id: "act_006_social_002", supports: ["ms_006_social_002","ms_006_social_003"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Mirror Hello", domain: "Social", time: "2-4 minutes", materials: "baby-safe mirror", why: "Face-focused routines support social attention and responsive caregiving.", steps: ["Sit with baby supported and facing a baby-safe mirror.", "Say hello to the reflection.", "Smile and pause.", "Name what baby does."], stop: "Use a baby-safe mirror. Stop if baby becomes overstimulated or uncomfortable." },
    { id: "act_006_language_001", supports: ["ms_006_language_001","ms_006_language_002"], evidence: "Mechanism-based", source: "Harvard + WHO", title: "Sound Turn-Taking", domain: "Language", time: "2-5 minutes", materials: "none", why: "Back-and-forth interaction supports attention, early communication and social learning.", steps: ["Hold baby where they can see your face.", "Wait for a sound, smile, kick, or expression.", "Copy it warmly.", "Pause and give baby time to respond."], stop: "Stop if baby turns away, cries, stiffens, coughs, or seems tired." },
    { id: "act_006_language_002", supports: ["ms_006_language_002"], evidence: "Mechanism-based", source: "Harvard + CDC", title: "Silly Sound Copy", domain: "Language", time: "2-4 minutes", materials: "none", why: "Copying baby’s bubbly or raspberry sounds encourages playful vocal exploration and turn-taking.", steps: ["Sit face-to-face with baby.","When baby makes a bubbly or squealing sound, copy it warmly.","Pause and wait.","Add one new playful sound and wait again."], stop: "Stop if baby turns away, coughs, or seems tired." },
    { id: "act_006_cognitive_001", supports: ["ms_006_cognitive_002","ms_006_movement_003"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Side Reach Toy", domain: "Learning", time: "3-5 minutes", materials: "one safe toy", why: "Reaching practice supports visual attention, arm control, body awareness and early problem-solving.", steps: ["Place baby on back, side-lying, tummy, or supported sitting.", "Hold a toy slightly to one side.", "Wait for looking, reaching, or body shift.", "Celebrate the attempt."], stop: "Avoid small or choking-risk items. Stop if baby is tired or frustrated." },
    { id: "act_006_cognitive_002", supports: ["ms_006_cognitive_003"], evidence: "Nurturing-care aligned", source: "CDC + WHO", title: "Responsive Feeding Pause", domain: "Learning", time: "during feeding", materials: "normal feeding setup", why: "Responsive caregiving helps baby's cues become meaningful in interaction.", steps: ["Offer food or milk as usual.", "Pause when baby slows down, closes mouth, or turns away.", "Name the cue calmly.", "Continue only if baby re-engages."], stop: "If feeding is stressful, painful, unsafe, or growth is a concern, speak with a professional." },
    { id: "act_006_movement_001", supports: ["ms_006_movement_002","ms_006_cognitive_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Straight-Arm Tummy Reach", domain: "Movement", time: "2-5 minutes", materials: "blanket and safe toy", why: "Brief supervised prone play supports head, shoulder and trunk control.", steps: ["Place baby awake and supervised on tummy.", "Put a toy in front and slightly to the side.", "Encourage looking, reaching, or pushing up.", "Keep it brief."], stop: "Only during awake supervised play. Never use tummy play during sleep." },
    { id: "act_006_movement_002", supports: ["ms_006_movement_003"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Tripod Sit Practice", domain: "Movement", time: "1-3 minutes", materials: "blanket and caregiver hands", why: "Supported sitting practice can support trunk control when baby shows readiness.", steps: ["Place baby on the floor with a caregiver close.", "Let baby lean on hands briefly.", "Place a toy in front.", "End before fatigue."], stop: "Stay close. Do not leave baby sitting alone. Stop if slumping or distress." }
  ],
  9: [
    { id: "act_009_social_001", supports: ["ms_009_social_005","ms_009_cognitive_001"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Peekaboo Pause", domain: "Social", time: "2-4 minutes", materials: "cloth or hands", why: "Peekaboo supports social anticipation, object permanence and turn-taking.", steps: ["Sit facing baby during calm awake time.", "Hide your face briefly.", "Reappear and smile.", "Wait for baby's response."], stop: "Stop if baby is startled or upset." },
    { id: "act_009_social_002", supports: ["ms_009_social_003"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Name Pause Game", domain: "Social", time: "1-2 minutes", materials: "none", why: "Name routines support social attention and caregiver observation.", steps: ["During normal play, call baby's name warmly once.", "Wait without repeating too quickly.", "Respond to any look or movement.", "Reduce background noise if needed."], stop: "If baby never responds to name or sounds, discuss with a provider." },
    { id: "act_009_language_001", supports: ["ms_009_language_001"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Babble Copy", domain: "Language", time: "2-5 minutes", materials: "none", why: "Imitative turn-taking supports early communication and sound play.", steps: ["Sit face-to-face or beside baby.", "Copy baby's sound string.", "Add a simple word.", "Pause for a response."], stop: "Stop if baby is tired or frustrated." },
    { id: "act_009_language_002", supports: ["ms_009_language_002"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Up Gesture Routine", domain: "Language", time: "1-2 minutes", materials: "none", why: "Consistent gesture routines support early communication before words.", steps: ["Before picking baby up, pause.", "Show open arms.", "Say up and wait.", "Respond to any reach or arm lift."], stop: "Stop if baby is upset or unsafe to wait." },
    { id: "act_009_cognitive_001", supports: ["ms_009_cognitive_001"], evidence: "Mechanism-based", source: "CDC 9 months", title: "Drop-and-Find Game", domain: "Learning", time: "2-5 minutes", materials: "safe spoon or toy", why: "Searching for dropped objects supports attention and object permanence.", steps: ["Sit with baby safely supported.", "Drop a toy within sight.", "Pause and ask where it went.", "Help baby look."], stop: "Use a safe object. Avoid throwing near the face. Stop if frustrated." },
    { id: "act_009_cognitive_002", supports: ["ms_009_cognitive_002"], evidence: "Mechanism-based", source: "CDC 9 months", title: "Two-Block Sound Play", domain: "Learning", time: "2-4 minutes", materials: "two safe light blocks or cups", why: "Banging two objects together supports cause-and-effect learning and hand coordination.", steps: ["Sit with baby supported.","Give one safe object to each hand.","Show how to bring them together to make a sound.","Pause and let baby try and explore."], stop: "Use safe non-breakable objects. Supervise. Stop if frustrated." },
    { id: "act_009_movement_001", supports: ["ms_009_movement_002","ms_009_cognitive_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Pass-the-Toy", domain: "Movement", time: "2-4 minutes", materials: "one easy-grip toy", why: "Object transfer supports bilateral coordination and exploration.", steps: ["Offer a toy at midline while baby sits supported or on the floor.", "Let baby take it.", "Offer from the other side.", "Wait for a transfer."], stop: "Stop if baby is tired. Avoid small parts." },
    { id: "act_009_movement_002", supports: ["ms_009_movement_004","ms_009_cognitive_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Sit-and-Reach Play", domain: "Movement", time: "2-5 minutes", materials: "safe toys", why: "Sitting with reach supports trunk control, balance and purposeful exploration.", steps: ["Place baby sitting on the floor with close supervision.", "Put toys slightly in front and to the side.", "Let baby reach.", "Let baby return to sitting."], stop: "Stay close. Avoid hard surfaces. Stop if baby slumps or falls repeatedly." }
  ],
  12: [
    { id: "act_012_social_001", supports: ["ms_012_social_001"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Pat-a-Cake Pause", domain: "Social", time: "2-4 minutes", materials: "none", why: "Simple social games support turn-taking, imitation and shared attention.", steps: ["Sit facing baby in a calm playful moment.", "Clap slowly and pause.", "Wait for baby to join.", "Copy any attempt."], stop: "Stop if baby loses interest or is frustrated." },
    { id: "act_012_social_002", supports: ["ms_012_social_001"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Copy-Me Clapping Game", domain: "Social", time: "2-4 minutes", materials: "none", why: "Imitation games like clapping and waving support turn-taking, imitation and shared joy.", steps: ["Sit facing baby.","Do a simple action: clap, tap the table, or wave.","Pause and invite baby to copy.","Cheer any attempt and take turns."], stop: "Stop if baby loses interest or is frustrated." },
    { id: "act_012_language_001", supports: ["ms_012_language_001"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Bye-Bye Routine", domain: "Language", time: "1 minute", materials: "none", why: "Repeated meaningful gestures support communication in everyday routines.", steps: ["Use a real departure or an object disappearing routine.", "Wave slowly.", "Say bye-bye.", "Pause for any gesture or look."], stop: "Do not drill. Stop if baby is upset by leaving." },
    { id: "act_012_language_002", supports: ["ms_012_language_002"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Name-and-Respond", domain: "Language", time: "2-3 minutes", materials: "none", why: "Responsive naming supports word meaning through warm repeated routines.", steps: ["During play, label caregiver names naturally.", "Say mama, dada, or the chosen caregiver name.", "Wait.", "Respond to baby's sound."], stop: "Stop if baby is frustrated. Avoid pressure to perform." },
    { id: "act_012_cognitive_001", supports: ["ms_012_cognitive_001"], evidence: "Mechanism-based", source: "CDC 12 months", title: "In-and-Out Container Play", domain: "Learning", time: "3-6 minutes", materials: "large blocks and container", why: "Container play supports problem-solving, hand use and cause-effect learning.", steps: ["Place a few large safe objects and a container on the floor.", "Show one object going in.", "Pause and let baby try.", "Dump out together."], stop: "Use non-choking objects. Supervise. Stop if frustrated." },
    { id: "act_012_cognitive_002", supports: ["ms_012_cognitive_002"], evidence: "Mechanism-based", source: "CDC + Harvard", title: "Hide-and-Find Toy", domain: "Learning", time: "2-5 minutes", materials: "toy and cloth", why: "Hide-and-find supports object permanence and shared attention.", steps: ["Let baby see you partly hide a toy under a cloth.", "Ask where it is.", "Pause.", "Let baby uncover it or help."], stop: "Stop if baby is upset. Avoid covering the face." },
    { id: "act_012_movement_001", supports: ["ms_012_movement_001","ms_012_movement_002"], evidence: "Mechanism-based", source: "CDC + WHO motor", title: "Stable Pull-to-Stand Play", domain: "Movement", time: "2-5 minutes", materials: "stable furniture", why: "Supported standing opportunities can support strength and balance when baby shows readiness.", steps: ["Use low stable furniture and stay close.", "Place a toy on a safe surface.", "Let baby pull or kneel if ready.", "Support as needed."], stop: "Use only stable furniture. Stay close. Stop if baby is tired or unsafe." },
    { id: "act_012_movement_002", supports: ["ms_012_movement_003"], evidence: "Mechanism-based", source: "CDC + WHO", title: "Pincer Snack Practice", domain: "Movement", time: "during meal", materials: "safe soft finger food", why: "Self-feeding practice supports fine motor control and responsive feeding.", steps: ["Seat baby safely for eating with a caregiver present.", "Offer one safe small soft food piece.", "Wait.", "Let baby attempt the pickup."], stop: "Use safe foods. Supervise closely. Follow choking guidance. Stop if unsafe." }
  ]
};
